# Generated by Django 4.2.2 on 2023-06-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=150)),
                ('difficulty', models.SmallIntegerField()),
                ('rating', models.SmallIntegerField()),
                ('cost', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals_app.meals')),
            ],
        ),
    ]
