# Generated by Django 4.2.2 on 2023-06-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meals',
            name='recipe_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='meals',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
