# Generated by Django 4.2.2 on 2023-07-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals_app', '0002_meals_description_alter_meals_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmeals',
            old_name='meal_date',
            new_name='date',
        ),
    ]
